from __future__ import annotations

from pydantic import BaseModel, Field


class GeneratedContextFile(BaseModel):
    """A file generated by the deterministic context generator."""

    name: str
    path: str
    description: str


class ProjectContext(BaseModel):
    """Structured project context generated from a repository scan."""

    workspace_path: str
    project_name: str
    project_type: str
    primary_language: str | None = None
    languages: list[str] = Field(default_factory=list)
    frameworks: list[str] = Field(default_factory=list)
    package_managers: list[str] = Field(default_factory=list)
    build_tools: list[str] = Field(default_factory=list)
    test_frameworks: list[str] = Field(default_factory=list)
    capabilities: list[str] = Field(default_factory=list)
    source_roots: list[str] = Field(default_factory=list)
    test_roots: list[str] = Field(default_factory=list)
    important_files: list[dict[str, str]] = Field(default_factory=list)
    generated_files: list[GeneratedContextFile] = Field(default_factory=list)
