from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any


@dataclass(frozen=True)
class AgentArtifact:
    """Artifact generated by a software development agent."""

    agent_id: str
    title: str
    path: str
    artifact_type: str
    generated_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return {
            "agent_id": self.agent_id,
            "title": self.title,
            "path": self.path,
            "artifact_type": self.artifact_type,
            "generated_at": self.generated_at,
            "metadata": self.metadata,
        }
